version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres123"
    volumes:
      - /var/lib/postgresql/data
      - ./projeto-site.sql:/docker-entrypoint-initdb.d/projeto-site.sql


